services:
  - type: web
    name: hotel-management-frontend
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://hotel-management-system-backend-k57q.onrender.com/api
